services:
  patient_management_application_mysql:
    image: mysql:8.1.0
    container_name: patient_management_application_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: patient_management_application
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_user
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

