name: Java CI with Maven

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      
      - name: Cache Maven and SonarCloud packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.sonar/cache
          key: ${{ runner.os }}-maven-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-sonar

      - name: Build, Test, and Analyze with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          mvn verify -Pjacoco,mutation-testing,coveralls \
          -Dsonar.projectKey=Talathussain110_management \
          -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }} \
          -DpullRequest=${{ github.event.pull_request.number }} \
          org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar
