name: Java CI with Maven

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      
      - name: Cache Maven and SonarCloud packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.sonar/cache
          key: ${{ runner.os }}-maven-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-sonar
